const stockProductos = [
    {
      id: 1,
      categoria:"Adidas",
      nombre: "Adidas Max Advantage",
      cantidad: 1,
      precio: 20000,
      img: "fotos/adidasMaxAdvantage.png",
    },
    {
      id: 2,
      categoria:"Adidas",
      nombre: "Adidas Air max Furiozas",
      cantidad: 1,
      precio: 15000,
      img: "fotos/air max furioza.png",
    },
    {
      id: 3,
      categoria:"Nike",
      nombre: "Nike Giannis Immortality",
      cantidad: 1,
      precio: 15700,
      img: "fotos/Giannis Immortality.png",
    },
    {
      id: 4,
      categoria:"New Balance",
      nombre: "New Balance Disrurt",
      cantidad: 1,
      precio: 13000,
      img: "fotos/new balance disrurt.png",
    },
    {
      id: 5,
      categoria:"Nike",
      nombre: "Nike Lebron",
      cantidad: 1,
      precio: 35000,
      img: "fotos/nike lebron.png",
    },
    {
      id: 6,
      categoria:"Nike",
      nombre: "Nike Ozelia",
      cantidad: 1,
      precio: 16000,
      img: "fotos/ozeliaa.png",
    },
    {
      id: 7,
      categoria:"Adidas",
      nombre: "Adidas Ozweego",
      cantidad: 1,
      precio: 14000,
      img: "fotos/Ozweego.png",
    },
    {
      id: 8,
      categoria:"DC",
      nombre: "DC Pure",
      cantidad: 1,
      precio: 12000,
      img: "fotos/pure.png",
    },
    {
      id: 9,
      categoria:"Adidas",
      nombre: "Adidas Yezze 750",
      cantidad: 1,
      precio: 14000,
      img: "fotos/yezze 750.png",
    },
    {
      id: 10,
      categoria:"DC",
      nombre: "DC Metric",
      cantidad: 1,
      precio: 9000,
      img: "fotos/dc metric.png",
    },
  ];
